### ISSUE TITLE
OpenSCAP CI started to comment on pull request

### ISSUE THREAD

**Issue by jan-cerny** [OpenSCAP/jenkins#37] opened 2017-11-06 17:00 UTC
OpenSCAP CI started to write comments into pull requests, which pollutes the discussion and makes pull requests harder to understand.

![screenshot from 2017-11-06 17-57-22](https://user-images.githubusercontent.com/9050916/32453383-54a2c6a6-c31c-11e7-90fe-e0069807b3fc.png)

**Comment by jan-cerny** [comment] 2017-11-06 17:06
https://github.com/OpenSCAP/scap-security-guide/pull/2444#issuecomment-342098328

**Comment by dahaic** [comment] 2017-11-10 16:44
To my understanding, the issue was caused by outdated `-pull-request` jobs - they used deprecated reporting option. By removing this option (done), messages are no longer posted to github. Closing now.

**Closed as completed** 2017-11-10 16:44 UTC
